server:
  listen_port: 8080
  max_connections: 1000

# Database configuration (reads from environment variables)
database:
  url: "${DATABASE_URL}"
  max_connections: 10
  min_connections: 2

# Redis configuration
redis:
  url: "${REDIS_URL}"
  pool_size: 10

# JWT configuration
jwt:
  secret: "${JWT_SECRET}"
  access_token_expiration: 900        # 15 minutes
  refresh_token_expiration: 604800    # 7 days

# Load balancing
load_balancing:
  strategy: "round_robin"  # Options: round_robin, random, least_conn
  upstreams:
    - name: "backend1"
      address: "127.0.0.1"
      port: 3000
      weight: 1
    
    - name: "backend2"
      address: "127.0.0.1"
      port: 3001
      weight: 1
    
    - name: "backend3"
      address: "127.0.0.1"
      port: 3002
      weight: 1

# Middleware configuration
middleware:
  auth:
    enabled: true
  
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst_size: 10